SELECT
   "Log"."id" AS "id"
  ,"Log"."date"
  ,"RecipeLog"."qty"
  ,"RecipeLog"."name"
  ,"RecipeLogProduct"."id"   AS "products:id"
  ,"RecipeLogProduct"."qty"   AS "products:qty"
  ,"RecipeLogProduct"."name"  AS "products:name"
  ,"RecipeLogProduct"."code"  AS "products:code"
  ,"RecipeLogProduct"."energy" AS "products:energy"
  ,"RecipeLogProduct"."fat"     AS "products:fat"
  ,"RecipeLogProduct"."saturated" AS "products:saturated"
  ,"RecipeLogProduct"."carbohydrates" AS "products:carbohydrates"
  ,"RecipeLogProduct"."sugar" AS "products:sugar"
  ,"RecipeLogProduct"."fiber" AS "products:fiber"
  ,"RecipeLogProduct"."proteins" AS "products:proteins"
  ,"RecipeLogProduct"."salt" AS "products:salt"
  ,"RecipeLogProduct"."serving" AS "products:serving"
  ,"RecipeLogProduct"."isIncomplete" AS "products:isIncomplete"
FROM "Log"
INNER JOIN "RecipeLog" ON "RecipeLog"."idLog" = "Log"."id"
LEFT JOIN "RecipeLogProduct" ON "RecipeLogProduct"."idRecipeLog" = "RecipeLog"."idLog"
