-- CreateTable
CREATE TABLE "Log" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "date" DATETIME NOT NULL,
    "type" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "WritingLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "comment" TEXT NOT NULL,
    "logId" INTEGER NOT NULL,
    FOREIGN KEY ("logId") REFERENCES "Log" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ExpenseLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "amount" REAL NOT NULL,
    "typeId" INTEGER NOT NULL,
    "comment" TEXT NOT NULL,
    "currencyId" INTEGER NOT NULL,
    "logId" INTEGER NOT NULL,
    FOREIGN KEY ("logId") REFERENCES "Log" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("typeId") REFERENCES "ExpenseType" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ExpenseType" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MovieLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "comment" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "logId" INTEGER NOT NULL,
    FOREIGN KEY ("logId") REFERENCES "Log" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "BookLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "comment" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "logId" INTEGER NOT NULL,
    FOREIGN KEY ("logId") REFERENCES "Log" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PhotoLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "comment" TEXT NOT NULL,
    "iso" INTEGER NOT NULL,
    "aperture" REAL NOT NULL,
    "speed" REAL NOT NULL,
    "film" TEXT,
    "logId" INTEGER NOT NULL,
    FOREIGN KEY ("logId") REFERENCES "Log" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "FoodLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "qty" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "code" INTEGER NOT NULL,
    "energy" INTEGER NOT NULL,
    "fat" INTEGER NOT NULL,
    "saturated" INTEGER NOT NULL,
    "carbohydrates" INTEGER NOT NULL,
    "sugar" INTEGER NOT NULL,
    "fiber" INTEGER NOT NULL,
    "proteins" INTEGER NOT NULL,
    "salt" INTEGER NOT NULL,
    "serving" INTEGER NOT NULL,
    "isIncomplete" BOOLEAN NOT NULL,
    "logId" INTEGER NOT NULL,
    FOREIGN KEY ("logId") REFERENCES "Log" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "FoodLogProduct" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "qty" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "code" INTEGER NOT NULL,
    "energy" INTEGER NOT NULL,
    "fat" INTEGER NOT NULL,
    "saturated" INTEGER NOT NULL,
    "carbohydrates" INTEGER NOT NULL,
    "sugar" INTEGER NOT NULL,
    "fiber" INTEGER NOT NULL,
    "proteins" INTEGER NOT NULL,
    "salt" INTEGER NOT NULL,
    "serving" INTEGER NOT NULL,
    "isIncomplete" BOOLEAN NOT NULL,
    "foodLogId" INTEGER NOT NULL,
    FOREIGN KEY ("foodLogId") REFERENCES "FoodLog" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
